# Generated by Django 5.2.1 on 2025-05-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('famili_id', models.AutoField(primary_key=True, serialize=False)),
                ('famili_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('famili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Budget_Application.families')),
            ],
        ),
        migrations.CreateModel(
            name='DataTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transaction', models.DateField()),
                ('income', models.FloatField(blank=True, null=True)),
                ('expense', models.FloatField(blank=True, null=True)),
                ('description', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='Budget_Application.users')),
            ],
        ),
    ]
