# Generated by Django 5.2.1 on 2025-05-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='USERS',
        ),
    ]
