# Generated by Django 5.2.2 on 2025-07-03 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTransactionView',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_surname', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('income', models.FloatField(blank=True, null=True)),
                ('expense', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('family_id', models.UUIDField()),
            ],
            options={
                'db_table': 'family_transaction_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CATEGORIES',
            },
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget_Application.categories'),
        ),
    ]
