# Generated by Django 5.2.1 on 2025-05-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Application', '0002_alter_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='families',
            old_name='famili_id',
            new_name='family_id',
        ),
        migrations.RenameField(
            model_name='families',
            old_name='famili_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='famili',
            new_name='family',
        ),
        migrations.RemoveField(
            model_name='datatransaction',
            name='type',
        ),
        migrations.AddField(
            model_name='datatransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='Budget_Application.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='datatransaction',
            table='DATA_TRANSACTION',
        ),
        migrations.AlterModelTable(
            name='families',
            table='FAMILIES',
        ),
    ]
