# Generated by Django 5.2.1 on 2025-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_test', '0002_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
