# Generated by Django 5.2.1 on 2025-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_test', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
