# Generated by Django 5.2.1 on 2025-05-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_test", "0007_joinrequest"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="familyinvitation",
            table="INVITATIONS",
        ),
        migrations.AlterModelTable(
            name="joinrequest",
            table="REQUESTS",
        ),
    ]
