# Generated by Django 5.2.1 on 2025-05-16 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'FAMILIES',
            },
        ),
    ]
