# Generated by Django 5.2.1 on 2025-05-16 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_test.family')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_test.user')),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
    ]
