# Generated by Django 5.2.1 on 2025-05-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_test', '0003_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_test.family'),
        ),
    ]
